list: $/bishopm/churchnet/models/denomination/columns.yaml
modelClass: Bishopm\Churchnet\Models\Denomination
title: Denomination
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'bishopm/churchnet/denomination/update/:id'
