title: Layleader
modelClass: Bishopm\Churchnet\Models\Layleader
list: $/bishopm/churchnet/models/layleader/columns.yaml
recordUrl: 'bishopm/churchnet/layleader/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
