title: Regional
modelClass: Bishopm\Churchnet\Models\Regional
list: $/bishopm/churchnet/models/regional/columns.yaml
recordUrl: 'bishopm/churchnet/regional/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: config_filter.yaml
