list: $/bishopm/churchnet/models/local/columns.yaml
modelClass: Bishopm\Churchnet\Models\Local
title: Local
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'bishopm/churchnet/local/update/:id'
